name: iOS Unsigned IPA Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios:
    name: Build Unsigned Flutter IPA
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Check Flutter
        run: flutter --version

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Install CocoaPods
        working-directory: ios
        run: pod install --repo-update

      - name: Build iOS Release Without Signing
        run: flutter build ios --release --no-codesign

      - name: Create Unsigned IPA
        run: |
          rm -rf Payload Unsigned-Flutter.ipa
          mkdir -p Payload
          cp -R build/ios/iphoneos/Runner.app Payload/Runner.app
          zip -qry Unsigned-Flutter.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-flutter-ipa
          path: Unsigned-Flutter.ipa
          if-no-files-found: error

      - name: Upload Runner App
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-runner-app
          path: build/ios/iphoneos/Runner.app
          if-no-files-found: error
